In [1]:
import pandas as pd

In [3]:
file_path = 'ntfrd.xlsx'
df = pd.read_excel(file_path, sheet_name='sheet1')
df.head()

,Provider ID,Operation ID,Payment ID,Operation Type,Operation Status,Secure 3ds Check,Channel Amount,Channel Currency,Operation created at Date,Payment Method Type,Account Number,Merchant ID,Project ID,Customer ID,Customer Email,Card Holder,Issuer Country Name,Country By IP Name,Customer IP V4 V6,Issuer Bank Name
0,4781.0,99892010097211,6021093719,sale,success,1.0,1000.0,RUB,2022-03-30,visa,427626******5062,39,321,3753071,avtomr@yandex.ru,LEONID PROKHOROV,Russian Federation,Russian Federation,176.59.134.184,SBERBANK of Russia
1,1293.0,99888010096111,347788572,sale,success,NaN,51.0,EUR,2022-02-27,visa,434597******0730,1581,5771,95022,williahmalexdelaplaza@gmail.com,WILLIAHM ALEX DE LA PLAZA,Denmark,Denmark,62.198.132.139,Jyske Bank A/S
2,1293.0,99888010096101,347788572,sale,decline,NaN,51.0,EUR,2022-02-27,visa,434597******0730,1581,5771,95022,williahmalexdelaplaza@gmail.com,WILLIAHM ALEX DE LA PLAZA,Denmark,Denmark,62.198.132.139,Jyske Bank A/S
3,1293.0,99888010096091,347788572,sale,decline,NaN,51.0,EUR,2022-02-27,visa,434597******0730,1581,5771,95022,williahmalexdelaplaza@gmail.com,WILLIAHM ALEX DE LA PLAZA,Denmark,Denmark,62.198.132.139,Jyske Bank A/S
4,1293.0,99888010096081,347788572,sale,decline,NaN,51.0,EUR,2022-02-27,visa,434597******0730,1581,5771,95022,williahmalexdelaplaza@gmail.com,WILLIAHM ALEX DE LA PLAZA,Denmark,Denmark,62.198.132.139,Jyske Bank A/S